spring:
  # Data Config
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/company
    username: root
    password: password